### ISSUE TITLE
Any Documenation?

### ISSUE THREAD

**Issue by hall-of-code** [lhmouse/asteria#111]
Hello,

I've seached for a Language Syntax Like Asteria for Months , but are there any "Example"-files or good Dokumentation? And whats about Sockets / Networking or Http Support?

:)

**Comment by lhmouse** [comment]
See <https://github.com/lhmouse/asteria/tree/master/asteria/doc> and <https://github.com/lhmouse/asteria/blob/master/asteria/test/proper_tail_call.cpp#L17>.

There is no plan on adding networking support. If you have any interest in integrating 3rd-party libraries you may add bindings yourself. An example is <https://github.com/lhmouse/asteria/blob/master/asteria/src/library/io.cpp>.

**Comment by hall-of-code** [comment]
Okay thanks

**Comment by lhmouse** [comment]
I have been composing some new documentation: https://github.com/lhmouse/asteria/blob/master/doc/quick-guide.md
