### ISSUE TITLE
Merge name lookups with in a whole expression

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/asteria#114]
For example in `x * x + y * y`. This is possible because expressions can't introduce new names.

**Comment by FrankHB** [comment]
This is a dedup, but not a merge.

Make `let` an expression and use [ANF](https://en.wikipedia.org/wiki/Administrative_Normal_Form).

**Comment by expnkx** [comment]
std::any and std::string LOL. the performance must be horrible.

**Comment by lhmouse** [comment]
This very simple expression compiles to `x x * y y * +` in RPN, which is

```text
                              # stack:
push_local_reference "x"      # (x)
push_local_reference "x"      # (x) (x)
apply_operator xop_mul        # (x*x)
push_local_reference "y"      # (x*x) (y)
push_local_reference "y"      # (x*x) (y) (y)
apply_operator xop_mul        # (x*x) (y*y)
apply_operator xop_add        # (x*x+y*y)
```

The stack is left with one reference to a temporary, which is the sum of the final addition.
If this is a full expression, it is not necessary to remove extra references beneath the result, so this can be transformed to

```text
                              # stack:
push_local_reference "x"      # (x)
push_local_reference "y"      # (x) (y)
push_back_reference -1        # (x) (y) (x)
push_back_reference -2        # (x) (y) (x) (x)
apply_operator xop_mul        # (x) (y) (x*x)
push_back_reference -1        # (x) (y) (x*x) (y)
push_back_reference -2        # (x) (y) (x*x) (y) (y)
apply_operator xop_mul        # (x) (y) (x*x) (y*y)
apply_operator xop_add        # (x) (y) (x*x+y*y)
```

**Comment by lhmouse** [comment]
I made a simple test and it turned out to run slower. I am putting this on suspension for now.

**Comment by expnkx** [comment]
std::any/std::unique_ptr = performance bug, definitely you have performance issues

**Comment by lhmouse** [comment]
> std::any/std::unique_ptr = performance bug, definitely you have performance issues

WTF are you mumbling about?

**Comment by expnkx** [comment]
> > std::any/std::unique_ptr = performance bug, definitely you have performance issues
> 
> WTF are you mumbling about?

smart pointers and any are losers' toy.

https://libcxx.llvm.org/docs/DesignDocs/UniquePtrTrivialAbi.html

![image](https://user-images.githubusercontent.com/57303909/110560791-94295d80-8114-11eb-94ba-e4ff631b7c22.png)

**Comment by lhmouse** [comment]
Closing this, because profiling (with `RDTSC`) discovered that name lookups and copy ctors of `Reference`  are on a par.

**Comment by FrankHB** [comment]
Given the suggested optimization is a non-trivial and important kind, I don't think there are sufficient reasons to close the issue. This should be reflect in the plan of improvement of the optimizations (if any).

**Comment by lhmouse** [comment]
Yeah you can reopen it.
