### ISSUE TITLE
Missing high-level plan of optimization

### ISSUE THREAD

**Issue by FrankHB** [lhmouse/asteria#115]
It seems that there is lacking a normative reference of overall optimizations, and by which criteria an issue related to the optimization can be closed.

For example, #114 needs to do the optimization of a kind of [local CSE](https://en.wikipedia.org/wiki/Common_subexpression_elimination). CSE is a common and general class of classical optimizations. When should such optimization class be involved?

**Comment by FrankHB** [comment]
Note this is mostly a doc issue, parallel to #81.

**Comment by lhmouse** [comment]
Now we need to find out how to optimize this:

![callgrind](https://github.com/lhmouse/asteria/assets/5071344/d9f977ee-c975-4bca-af5c-786b7b39207f)

**Comment by lhmouse** [comment]
Closing as a duplicate of the other.
