### ISSUE TITLE
`each` clause in `switch` statements

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/asteria#312]
Change
```text
switch-clause ::=
	( "case" expression | "default" ) ":" statement *
```
to
```
switch-clause ::=
	( "default" | "case" expression | "each" ( "[" | "(" ) expression ","
	expression ( "]" | ")" ) ) ":" statement *
```

with the following semantics:

```text
switch(expression)
  {
  each [foo, bar):
    /* clause */;
  }
```
The clause is executed if `(expression >= foo) && (expression < bar)` evaluates to true. `[` and `]` denote a closed interval and `(` and `)` denote an open interval.

**Comment by XR-stb** [comment]
i want to try! 😁, but let me first learning some asteria token and parser code. can you give me some guide ? （￣︶￣）↗

**Comment by lhmouse** [comment]
> i want to try! 😁, but let me first learning some asteria token and parser code. can you give me some guide ? （￣︶￣）↗

You may search for `switch_clause` in 'asteria/'. There are actually two structs, in `Statement` and `AIR_Node`, with this same name; these will give you an overview about how a `switch` statement is implemented.
