### ISSUE TITLE
standard streams and locales

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/asteria#51]
At the moment a number of features (e.g. `std.debug.dump()` and exceptional messages) depend on `rocket::insertable_ostream`, which implements `std::ostream`. As it copies the global locale object upon construction, which can be altered by the user with `std::locale::global()`, it is not safe to rely on its behavior. An example where this matters is that in every European language other than English, the decimal separator is a comma(`,`) rather than a period(`.`). A permanent solution to this issue shall be taken into account.

**P.S.** Only output streams have this issue. The only functions in Asteria that take `std::istream` as inputs are the constructor of `Simple_Source_File` and `Simple_Source_File::reload()`, which operates on the `streambuf` directly w/o regard to the locale object stored in the stream.

**Comment by FrankHB** [comment]
Always switch to the "C" locale to be sane, and avoid the stupid `std::locale` interface as possible.

Moreover, render the behavior undefined if the locale is altered unexpectedly.

**Comment by lhmouse** [comment]
> Always switch to the "C" locale to be sane, and avoid the stupid `std::locale` interface as possible.
> 
> Moreover, render the behavior undefined if the locale is altered unexpectedly.

Invoking `my_stream.imbue(std::locale::classic())` after constructing every stream object looks stupid. Moreover, the concept of standard C++ streams, which depends on hard-coded order of function calls, is retarded enough that it can seldom support any sane i18n implementation such as **gettext**. Taking locales into account does not render them usable. I agree with you on that altering the global locale results in undefined behavior.
