### ISSUE TITLE
[RFC] Module system

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/asteria#68]
We may take [Node.js](https://nodejs.org/api/modules.html) as an example.

### Considerations

1. What will happen if modules reference each other recursively and infinitely?

**Comment by MaskRay** [comment]
There are other module systems we can take inspiration from, e.g. [D](https://dlang.org/spec/module.html), [Julia](https://docs.julialang.org/en/v1/manual/modules/index.html), and [Lua](https://www.lua.org/manual/5.3/manual.html#6.3).

**Comment by lhmouse** [comment]
I would expect imported modules to be visible globally e.g. by making them names in the global context. This allows us to detect recursive dependencies and bail out if the request is recursive. Scoped `import`s such as in D don't seem to be an option.

**Comment by lhmouse** [comment]
### Proposed Syntax

```js
import mod ("/path/to/some/script", with, some, arguments);
```

### Formal Grammar

```text
import-statement ::=
    "import" identifier postfix-function-call ";"
```

### Semantics

The _import-statement_ attempts to open the script file designated by its first argument, which shall be a string representing a valid path. The file is read, parsed and executed as a function, whose return reference is converted to a prvalue and used to initialize the immutable variable that is being declared by this _import-statement_. If the script returns void, the variable is initialized to `null`. Arguments are passed to the script file, except the first one (the path) which is always converted to an absolute path.

If a script that is being loaded loads itself recursively, an exception is thrown.

**Comment by lhmouse** [comment]
This way it had better be a library function.

**Comment by FrankHB** [comment]
> 
> 
> This way it had better be a library function.

Better update the rationale for the decision here.

**Comment by FrankHB** [comment]
> If a script that is being loaded loads itself recursively, an exception is thrown.

Minor: is "script" a normative term in the specification currently?

**Comment by lhmouse** [comment]
> Minor: is "script" a normative term in the specification currently?

No.

Looks like this cannot be a library function for two reasons:

1. One is that the callee cannot obtain a copy of the `Compiler_Options` of the caller, as it is lost during translation time. One possible solution to this issue is to provide the options object in the `Global_Context`, but see below.
2. The other is that, when a relative path is given, one usually expects `import` to locate the target script file relative to the _caller_, which the callee has no knowledge about either. Unlike the issue above, such information is kept at run time but cannot be delivered across function boundaries.

This concludes the necessity that we have to have sort of syntax construction that effectively captures such metadata from translation to runtime.

**Comment by FrankHB** [comment]
> when a relative path is given, one usually expects import to locate the target script file relative to the caller

No. The expected actual path of the module directory should be well-known by convention (either fixed locations or specified by some environment variables for example). Even if it denotes the current working directory, it *should* be a part of global states, as the usual shell scripts do.

And I don't see what do you mean exactly about the *caller*. Is it the function or the source file which initiate the effect of "import"?

**Comment by lhmouse** [comment]
> No. The expected actual path of the module directory should be well-known by convention (either fixed locations or specified by some environment variables for example). Even if it denotes the current working directory, it should be a part of global states, as the usual shell scripts do.

Why do you consider environment variables a _good_ example, such as the infamous `GOPATH`?

The working directory may be changed (for example by `daemon()`) which could result in confusion. There has already been some cautionary tales such as PHP's  `include()` which is always relative to the script file _being accessed_ (not the file _containing_ the `include` statement).

> And I don't see what do you mean exactly about the caller. Is it the function or the source file which initiate the effect of "import"?

The latter.

**Comment by FrankHB** [comment]
> Why do you consider environment variables a _good_ example, such as the infamous `GOPATH`?

I never think it is. That is not just _that_ bad, compared to keeping a hard-code path as a potentially brain-damaged hole _unconditionally inside_ the source tree of the programs with no way to override. This is more important when the referenced modules are _deployed_ out of the source tree. (Consider why [FHS](https://en.wikipedia.org/wiki/Filesystem_Hierarchy_Standard) uses well-known path prefixes, for example.)
.
CWD is bad for both uses, for sure.

> 
> The working directory may be changed (for example by `daemon()`) which could result in confusion. There has already been some cautionary tales such as PHP's `include()` which is always relative to the script file _being accessed_ (not the file _containing_ the `include` statement).
> 
> > And I don't see what do you mean exactly about the caller. Is it the function or the source file which initiate the effect of "import"?
> 
> The latter.

Then the callee can naturally share the information about the information fromthe caller without significant overhead.

**Comment by lhmouse** [comment]
> Then the callee can naturally share the information about the information from the caller without significant overhead.

The callee cannot obtain any information about its caller (not even the evaluation stack). This isolation is intentional.
