### ISSUE TITLE
Optimization techniques

### ISSUE THREAD

**Issue by lhmouse** [lhmouse/asteria#81]
### Optimizer Wish List

- [x] Tail and Sibling Call Optimization (_abbr. mistakenly_ **TCO**)
    Note that _proper tail calls_ are a core language feature that cannot be disabled.

- [x] Dead Code Elimination (_abbr._ **DCE**)
    This had been implemented naively but was withdrawn. It can be added back easily. But before that, rather than having individual interfaces for varieties of optimization techniques, I would prefer to have a uniformed interface for `cow_vector<AIR_Node>`, which may be invoked recursively.

- [x] Constant Folding
    Ideally this pass should precede DCE. We may also support _constant expressions_ (such as `1+2*3`) in the future. Arithmetic overflows (such as `1<<100`), if not folded, result in exceptions, so we must not fold such expressions.

- [ ] #137

**Comment by FrankHB** [comment]
[Metacompilation](https://en.wikipedia.org/wiki/Metacompilation)

**Comment by FrankHB** [comment]
What is the state of PTC support on mutual recursive calls?

**Comment by lhmouse** [comment]
> What is the state of PTC support on mutual recursive calls?

A function call is flattened if it occurs in a PTC context, regardless of being recursive or not.

Examples:

```go
func foo() {
  if(something) {
    return other(1, 2, 3);  // PTC by value (the result is an rvalue)
  }
  if(something) {
    return& other(4, 5, 6);  // PTC by reference (the result is forwarded as is)
  }
  if(something) {
    other(true, false);  // PTC by nullification (the result is discarded)
    return;
  }
  other("hello");  // PTC by nullification
}
```

**Comment by lhmouse** [comment]
info: According to profiling results by callgrind, the most hot piece of code seems to be copying `Reference`s.
