### ISSUE TITLE
吱吱快来使用fast_io库做asteria的内核

### ISSUE THREAD

**Issue by expnkx** [lhmouse/asteria#95]
这样你就省事了。我Hack了所有主流libc和libc++的内部实现。

https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/cpp/fp_hack/libc%2B%2B.h

https://github.com/expnkx/fast_io/blob/master/include/fast_io_legacy_impl/c/glibc.h

**Comment by lhmouse** [comment]
You **shall** not rely on any implementation details of your compiler or standard library. If there's really necessity that you cannot utilize such facilities, you should provide your alternative without hacking.

**Comment by expnkx** [comment]
> You **shall** not rely on any implementation details of your compiler or standard library. If there's really necessity that you cannot utilize such facilities, you should provide your alternative without hacking.

既提供了alternative又提供了hacking。如果不hacking你现有代码就跑不起来了。
